
services:
  app:
    container_name: reddit-sentiment-ananlyzer
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - DOCKERIZED=true  # Flag to tell the app it's running inside Docker
    volumes:
      - ./models:/app/models  # Mount models directory from host to container
    # GPU support for NVIDIA GPUs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  mongo:
    image: mongo:latest
    container_name: reddit_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo_data:
